DROP TABLE IF EXISTS AUTHORS;
DROP TABLE IF EXISTS GENRES;
DROP TABLE IF EXISTS BOOKS;
CREATE TABLE AUTHORS(ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY, AUTHOR VARCHAR(70));
CREATE TABLE GENRES(ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY, GENRE VARCHAR(20));
CREATE TABLE BOOKS(ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY, TITLE VARCHAR(100), AUTHOR BIGINT REFERENCES AUTHORS(ID), GENRE BIGINT REFERENCES GENRES(ID));